### ISSUE TITLE
[18615] [23-04 12:57:10] [pipeline.article_grab_module] [CRITICAL] pen.n.01, [Errno 2] No such file or directory: '../output/url/pen.n.01.txt'

### ISSUE THREAD

**Issue by puraminy** [phongnt570/ascent#1]
I installed and tried the project, but it seems it doesn't generate any output, instead, it says there is no output file.

```


Enter subjects: pen.n.01
[18615] [23-04 12:57:05] [__main__] [INFO] Running pipeline for 1 subjects: [pen.n.01]
[0] Bing Search
[1] Crawl articles
[2] Filter irrelevant articles
[3] Extract knowledge
[4] Cluster similar triples
[5] Label facets
[6] Group similar facets
From module: 0
  To module: 1
[18668] [23-04 12:57:09] [pipeline.bing_search_module] [INFO] Subject pen.n.01 - Bing search
[18668] [23-04 12:57:09] [retrieval.bing_search] [INFO] Subject pen.n.01 - Search query: `what is pen?`
[18668] [23-04 12:57:10] [retrieval.bing_search] [INFO] Detected manual WordNet-Wikipedia linking
[18668] [23-04 12:57:10] [pipeline.bing_search_module] [CRITICAL] pen.n.01, list assignment index out of range
[18615] [23-04 12:57:10] [pipeline.article_grab_module] [INFO] Subject pen.n.01 - Crawl relevant articles
[18615] [23-04 12:57:10] [pipeline.article_grab_module] [CRITICAL] pen.n.01, [Errno 2] No such file or directory: '../output/url/pen.n.01.txt'

```

**Comment by phongnt570** [comment]
Did you provide the Bing API Key and Bing Search Custom Config in your config file?

**Comment by puraminy** [comment]
Here are part of my config.ini

```
bing_search]
subscription_key = AozO0YRFegui0Omx09ttFarMuCgAGxdrGpM4CEK7cv7rOpnGalOr6QUkl_7Qv9rT 
custom_config = [bing_search]
num_urls = 10
host = api.cognitive.microsoft.com
path = /bingcustomsearch/v7.0/search
overwrite = false
num_processes = 1
```

I didn't know where I should find the key, I just followed this:

https://docs.microsoft.com/en-us/bingmaps/getting-started/bing-maps-dev-center-help/getting-a-bing-maps-key

Is it free? I must also say that I am in Iran! How can I test if my key works?

**Comment by phongnt570** [comment]
Currently we use the Bing Custom Search API (https://docs.microsoft.com/en-us/rest/api/cognitiveservices-bingsearch/bing-custom-search-api-v7-reference). Though, I'm not sure if they have a free plan. As we use a paid plan, we cannot share our own keys to the public.
You can also check this function (https://github.com/phongnt570/ascent/blob/main/src/retrieval/bing_search.py#L90) to see how we call the API.

**Comment by puraminy** [comment]
Thank you very much, I will investigate that. Since I'm in Iran, we have no international credit cards to use some services. Anyways, could I replace it with any other search engine? Can I have such functionality from google or other websites which provide free keys? Should I then change parts of the code?

**Comment by phongnt570** [comment]
No problem!

Sorry for the situation, and yes, definitely, you can replace with any search engine by changing the code of this function `search_for_subject` (https://github.com/phongnt570/ascent/blob/main/src/retrieval/bing_search.py#L21)

The function should return:
- `results`: list of tuples (url, title, snippet)
- `wiki`: title of reference Wikipedia article (e.g., Lion)
- `wiki_map_source`: a string indicating the source where the reference Wikipedia article was taken from

As you can see the function is called only once here (https://github.com/phongnt570/ascent/blob/main/src/pipeline/bing_search_module.py#L87). Therefore, editing that function would be sufficient.

**Comment by puraminy** [comment]
Thank you, I'll try it... just could you give an example? what is snippet?

**Comment by phongnt570** [comment]
Snippet is just the text snippet that Google shows under each URL. E.g.:

`url` = _https://en.wikipedia.org/wiki/Lion_
`title` = _Lion - Wikipedia_
`snippet` = _The lion (Panthera leo) is a species in the family Felidae and a member of the genus Panthera...._
