### ISSUE TITLE
License for code

### ISSUE THREAD

**Issue by huu4ontocord** [phongnt570/ascent#4]
Hi @phongnt570 ! This is a great library. I'd like to use it in the BigScience workshop. https://github.com/bigscience-workshop Would it be possible to release this code as Apache 2.0?

**Comment by phongnt570** [comment]
Yes, sure. You can release it as Apache 2.0.

**Comment by huu4ontocord** [comment]
Awesome! Thank you. Whenever you get a chance, can you put the Apache 2.0 LICENSE file in the repo https://www.apache.org/licenses/LICENSE-2.0 please?

**Comment by phongnt570** [comment]
Thanks. I added the License.

**Comment by huu4ontocord** [comment]
Thank you!
